version: '3.8'    #check if there is a new docker compose version
services:
  web:
    build:
        context: ./
        dockerfile: docker/apache.docker
    # image: php:8.3-apache    #check the php version you need for your project
    ports:
      - "80:80"    #this line maps your pc port to the container port
    volumes:
      - ./html:/var/www/html    #this line maps the content of ./html in your pc to the /var/www/html of the container
